### ISSUE TITLE
Add support for env file 

### ISSUE THREAD

**Issue by rajinish01** [deep-compute/basescript#108]
- User should be able to provide an env variable that will be appended to every logline

refer: https://github.com/nudjur/infra/issues/307

**requirements**

- Add a command-line argument to accept the env file
- env file will be a dictionary in YAML configuration
- whenever a signal is received it should read the env variables from the <>.yaml file and update the log line

**Comment by rajinish01** [comment]
![Screenshot 2021-09-24 at 12 06 02 PM](https://user-images.githubusercontent.com/30134936/134629260-35bb0f77-a193-4070-bb45-39938a3b25fd.png)

log lines are being updated as per the env file 

env file is a dictionary in yaml format

**env.yaml**
```yml
hostname: "hostname_changed"
session_id: "1234567890"
ip_address: "95.217.211.79"
```
**test_script.py**
```python3
from basescript import BaseScript
from time import sleep


class HelloWorld(BaseScript):
    def run(self):
        for _ in range(100000):
            self.log.info("test_env_file_{}".format(_))
            sleep(1)


if __name__ == "__main__":
    HelloWorld().start()
```
**run command**

```bash
python3 test_script.py --log-level DEBUG --log-file  log.log --env-file env.yaml run
```
- type below command to get process id

```bash
ps aux | grep -i test_script.py
```
- Send kill signal to the process 
```bash
kill -s USR1 <PID>
```

**Comment by rajinish01** [comment]
PR ready for review

**Comment by sundarrajan78** [comment]
@rajinish01 Can you post update?

**Comment by rajinish01** [comment]
pending for rewivew

**Comment by rajinish01** [comment]
@sundarrajan78 I was not able to merge the PR as `continuous-integration/travis-ci ` was struck, can you please help me merge the PR, merge is not visible to me I think admins can push them.

![Screenshot 2021-09-29 at 5 38 21 AM](https://user-images.githubusercontent.com/30134936/135181738-8322e4c6-ad39-4912-a76e-3ce5e25370b9.png)

**Comment by rajinish01** [comment]
closing this issue as it's been merged to master

**Comment by nudjur-ops** [comment]
test
