### ISSUE TITLE
basescript entrypoint for extensions

### ISSUE THREAD

**Issue by algrebe** [deep-compute/basescript#5]
add an entry point `basescript.extensions` where all extensions can register.
they have to be subclasses of Basescript.

**Comment by jaswanth098** [comment]
Not working actively on this  will get back when I can

**Comment by jaswanth098** [comment]
not prio

**Comment by sundarrajan78** [comment]
Not a priority

**Comment by sundarrajan78** [comment]
Not a priority

**Comment by sundarrajan78** [comment]
Low Priority

**Comment by sundarrajan78** [comment]
Low priority
