### ISSUE TITLE
Can't use basescript in project

### ISSUE THREAD

**Issue by debolinakar** [deep-compute/basescript#61]
1. Tabs and spaces got mixed and we are getting indentation error
2. Cant import init_logger and get logger.
![basescripterror](https://user-images.githubusercontent.com/35727020/37957142-d68e08d4-31ca-11e8-9297-0d1a361685c9.png)

**Comment by ghost** [comment]
@debolinakar 
* We resolved this issue in a new release of `Basescript-0.2.4` so we can close this ticket.
