### ISSUE TITLE
Metric-grouping with dictionaries inside a metric.

### ISSUE THREAD

**Issue by ghost** [deep-compute/basescript#62]
#### Read-Me:
* If there is dictionary inside the metric we are facing an issue while metric-grouping with the new basescript logic, we have to support if there is a `dictionary/nested-dictionary` inside a metric for grouping.
#### Error:
![37890086-d19a1cf2-30ec-11e8-9dda-c582b93d96f8](https://user-images.githubusercontent.com/16955073/38012227-33f8884c-327e-11e8-8171-2042846e007f.png)

**Comment by jaswanth098** [comment]
Not working actively on this moving this to ready-status

**Comment by sundarrajan78** [comment]
@jaswanth098 Is there any action required. Can we close it?

**Comment by jaswanth098** [comment]
This has to be done we are not currently taking up tasks here

**Comment by sundarrajan78** [comment]
@jaswanth098 I am assigning this to you and snoozing it for 1 month
