### ISSUE TITLE
Storing of logs

### ISSUE THREAD

**Issue by Anjali0211** [deep-compute/basescript#67]
On setting the fmt = 'pretty', the logs are being stored in pretty format in the web.log file instead of json format.

![base](https://user-images.githubusercontent.com/35727020/38554197-3c80be6a-3cdf-11e8-9c57-0f5e4847ba4e.png)

**Comment by ghost** [comment]
@Anjali0211 
* Thanks for reporting the problem which you are facing we will fix this in the next release.

**Comment by ghost** [comment]
* This issue is resolved we can close this ticket.
