### ISSUE TITLE
#Feature: Auto json conversion using pipe(|).

### ISSUE THREAD

**Issue by ghost** [deep-compute/basescript#68]
#### Read-Me:
* As per discussion with @prashanthellina while running the `Basescript` code intially it will write `pretty` format logs to the console.
![screen shot 2018-04-11 at 3 15 36 pm](https://user-images.githubusercontent.com/16955073/38609253-3864c9c2-3d9b-11e8-8c43-66406a233a6b.png)
* If we specify pipe(|) after the command it must print `json` format to the console.
ex: `python test.py run | jq -C . | less -R`

**Comment by supriyopaul** [comment]
Can you do the reverse too?
Like for a given log file I can pipe it with `basescript pretty`
![image](https://user-images.githubusercontent.com/33823698/42155751-d6396a76-7e06-11e8-85f9-ee15fe795955.png)
![image](https://user-images.githubusercontent.com/33823698/42155775-ebcca25e-7e06-11e8-94fc-2c4b698d1c87.png)

Below is the code for pretty.py can you please make it a command line tool?

```
import sys                                                                                                                                                                               
import ujson as json                                                                                                                                                                     
from structlog.dev import ConsoleRenderer                                                                                                                                                
                                                                                                                                                                                         
def main():                                                                                                                                                                              
    c = ConsoleRenderer()                                                                                                                                                                
    for line in sys.stdin:                                                                                                                                                               
        d = json.loads(line)                                                                                                                                                             
        print(c(None, None, d))                                                                                                                                                          
                                                                                                                                                                                         
if __name__ == '__main__':                                                                                                                                                               
    main()
```

**Comment by supriyopaul** [comment]
Any status on the feature of making basescript logs inside files more readable? I need it for debugging.

**Comment by ghost** [comment]
@supriyopaul 
* We have a high priority works of deepfetch because of that we didn't work on it yet. so will do it later or else if you are free you can do it and give me a pull I will review it.

**Comment by jaswanth098** [comment]
Not working on this actively

**Comment by sundarrajan78** [comment]
@jaswanth098 I am snoozing this for 1 month.

**Comment by sundarrajan78** [comment]
Lower Priority

**Comment by sundarrajan78** [comment]
@prashanthellina Can we close this issue?

**Comment by prashanthellina** [comment]
I'll track it.

**Comment by prashanthellina** [comment]
Will attempt tomorrow

**Comment by prashanthellina** [comment]
Missed this one. Will attempt.

**Comment by prashanthellina** [comment]
> Can you do the reverse too?
> Like for a given log file I can pipe it with `basescript pretty`
> ![image](https://user-images.githubusercontent.com/33823698/42155751-d6396a76-7e06-11e8-85f9-ee15fe795955.png)
> ![image](https://user-images.githubusercontent.com/33823698/42155775-ebcca25e-7e06-11e8-94fc-2c4b698d1c87.png)
> 
> Below is the code for pretty.py can you please make it a command line tool?
> 
> ```
> import sys                                                                                                                                                                               
> import ujson as json                                                                                                                                                                     
> from structlog.dev import ConsoleRenderer                                                                                                                                                
>                                                                                                                                                                                          
> def main():                                                                                                                                                                              
>     c = ConsoleRenderer()                                                                                                                                                                
>     for line in sys.stdin:                                                                                                                                                               
>         d = json.loads(line)                                                                                                                                                             
>         print(c(None, None, d))                                                                                                                                                          
>                                                                                                                                                                                          
> if __name__ == '__main__':                                                                                                                                                               
>     main()
> ```

The expectation from the issue description is already supported now.  The quote comment above is what needs to be handled.

**Comment by prashanthellina** [comment]
The first step is to make `basescript` a command line tool (currently it is just a python package that can be imported for use). Once done, the next step will be to support the `pretty` sub-command.

**Comment by prashanthellina** [comment]
PR issued. Awaiting approval + merge + release.

**Comment by ManishaBayya** [comment]
PR is ready to be merged. But I don't have clarity on automation that is there in this repo for PyPI and Github release. Do we have to make those releases manually? or Travis still works?

**Comment by sundarrajan78** [comment]
@ManishaBayya We will discuss today to bring this issue to closure

**Comment by ManishaBayya** [comment]
Travis checks don't seem to be working.

![Screenshot from 2021-07-07 11-31-28](https://user-images.githubusercontent.com/34313380/124708216-97dcbd80-df17-11eb-9960-5d3b43c77330.png)

Even to make a manual Github release merging is blocked because the Travis checks didn't happen. We will have to change the settings of repo to remove the constraint of checks to be passed for merges. For this, we don't have proper permissions.

**Comment by prashanthellina** [comment]
> Even to make a manual Github release merging is blocked because the Travis checks didn't happen. We will have to change the settings of repo to remove the constraint of checks to be passed for merges. For this, we don't have proper permissions.

Gave admin access to @sundarrajan78. I force merged and made a github release. Please ensure that PyPI release was done for this too if not go ahead and do it.

**Comment by shivam05011996** [comment]
I Will look into it later today, working on priority on https://github.com/nudjur/backend/issues/644.

**Comment by shivam05011996** [comment]
Looking into this.

**Comment by shivam05011996** [comment]
Made the test release to `https://test.pypi.org/legacy/` upload and installation was successful
Made the release to private PyPI at `http://pypi.deepcompute.com/simple` upload and installation was successful

Uploading to global PyPI did not go through because of some authentication errors and few invalid URLs - 
![image](https://user-images.githubusercontent.com/33828942/125398525-0fee2c00-e3cd-11eb-8e99-9ca42400126b.png)

**Comment by shivam05011996** [comment]
Have uploaded to global PyPi, I was using the wrong credentials.  @prashanthellina Can we close this.?

**Comment by prashanthellina** [comment]
@shivam05011996 Thank you. Will upload to PyPI happen automatically next time?

**Comment by shivam05011996** [comment]
We need to configure GitHub actions for that @prashanthellina . Earlier we used to have Travis for this.

**Comment by prashanthellina** [comment]
Thank you @shivam05011996
