### ISSUE TITLE
Not printing "debug" Logs in 0.2.4 version.

### ISSUE THREAD

**Issue by Venkatesh-283** [deep-compute/basescript#70]
![basescript](https://user-images.githubusercontent.com/34322575/38681344-0c072fb4-3e86-11e8-9b0f-4fdadd1fd33e.png)
In version 0.2.1 It is printing all logs. 
In 0.2.4 It is not printing debug logs alone.

**Comment by ghost** [comment]
@Venkatesh-283 
* We fix this issue in the new release(0.2.5) please update your `basescript` version.
* This issue is resolved so, we can close this ticket.
