### ISSUE TITLE
#Feature: Per process stats.

### ISSUE THREAD

**Issue by ghost** [deep-compute/basescript#75]
### Read-Me:
* If a service is running using `Basescript` we have to write that service stats logs(ram, cpu, swap, ..) by default to a separate log file.

**Comment by jaswanth098** [comment]
not actively working on this

**Comment by sundarrajan78** [comment]
Snoozing this for 3 months. DataDog might help us here.

**Comment by prashanthellina** [comment]
No longer relevant because we use docker and containerstats.
