### ISSUE TITLE
#Feature: Explore click module in basescript.

### ISSUE THREAD

**Issue by ghost** [deep-compute/basescript#77]
## Read-me:
* The new `click` module read command line arguments with more features we have to understand more about it and then decide to explore it or not.
**Refer:** http://click.pocoo.org/5/why/#

**Comment by jaswanth098** [comment]
We are not actively working on this moving this to ready-status for now

**Comment by sundarrajan78** [comment]
Low priority

**Comment by sundarrajan78** [comment]
Not a priority

**Comment by sundarrajan78** [comment]
Snoozing for 3 months

**Comment by sundarrajan78** [comment]
Low priority
