### ISSUE TITLE
Document: Sub Commands

### ISSUE THREAD

**Issue by prashanthellina** [deep-compute/basescript#82]
This is a often used feature but is hidden now as we lack documentation or even an example

**Comment by ghost** [comment]
* Currently we are working on other projects so we pause work on this so will do it later.

**Comment by jaswanth098** [comment]
Not actively working on this

**Comment by sundarrajan78** [comment]
@jaswanth098 Snoozing this for amonth

**Comment by sundarrajan78** [comment]
Low priority

**Comment by sundarrajan78** [comment]
Low priority

**Comment by sundarrajan78** [comment]
Low priority

**Comment by sundarrajan78** [comment]
Low priority
