### ISSUE TITLE
Document: Logging guidelines

### ISSUE THREAD

**Issue by prashanthellina** [deep-compute/basescript#83]
Basescript supports structured logging based on `structlog` (https://www.structlog.org/en/stable/why.html). However, the documentation here does not list the capabilities and the best practices for logging (eg: every log is an event and the string should look like an identifier; values most not be encoded into this string but instead logged a kv pairs etc)

**Comment by ghost** [comment]
* Currently we are working on other projects so we pause work on this issue.

**Comment by sundarrajan78** [comment]
Assigned to @jaswanth098 as Rajendra is no longer with us

**Comment by sundarrajan78** [comment]
Lower pririorty

**Comment by sundarrajan78** [comment]
Low priority

**Comment by sundarrajan78** [comment]
Low priority
