### ISSUE TITLE
TypeError: init_logger() got an unexpected keyword argument 'pre_hooks'

### ISSUE THREAD

**Issue by prasannababuAddagiri** [deep-compute/basescript#98]
- we got the below issue when ran the sample hello_world.py which is in README 
- TypeError: init_logger() got an unexpected keyword argument 'pre_hooks'
![image](https://user-images.githubusercontent.com/28616976/65011843-a6b54300-d932-11e9-86fc-8e4b4a081f21.png)
- basescript version(0.3.3)
![image](https://user-images.githubusercontent.com/28616976/65011871-c0568a80-d932-11e9-8ef5-3811f31d5c36.png)

**Comment by jaswanth098** [comment]
@prashanthellina pre_hooks and post_hooks support has been removed was this intentional?
Ref: https://github.com/deep-compute/basescript/pull/94/files#diff-dc82fce42548e16e9b4331cd2c343753R361

**Comment by prashanthellina** [comment]
My bad. I did want to replace `pre_hooks` and `post_hooks` by just `processors` but looks like I missed testing this aspect of it (i.e. I tested only calling `init_logger` directly). Will fix this today.

**Comment by prashanthellina** [comment]
@jaswanth098 Applied the fix. Please review, merge and release.

**Comment by prashanthellina** [comment]
@prasannababuAddagiri : @jaswanth098 made a release with the fix. Can you please take the latest version and try again?

**Comment by jaswanth098** [comment]
@prasannababuAddagiri This has been fixed and pushed to PyPi, please check this out with the latest version
Closing this as this is fixed, feel free to open this issue if needed

**Comment by prasannababuAddagiri** [comment]
sure @prashanthellina @jaswanth098. will test now.
